### ISSUE TITLE
MOBILE RESPONSIVENESS

### ISSUE THREAD

**Issue by aubstacle** [RFlanagan82/gameknight#187]

**Comment by aimeecesler** [comment]
create new event form - date and time pickers overrun the card. I think it's something to do with the container inside the container fluid which we don't need anymore without the parchment background.

**Comment by aimeecesler** [comment]
home page 
- logo in jumbotron image need @media sizing to make it smaller at smaller screen sizes

**Comment by aimeecesler** [comment]
events page - something funky with the card header on the event listing card, text is overrunning it (card body is fine)
